# ===============================
# Application Configuration
# ===============================
spring.application.name=astra-ai

# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/astra_ai
spring.datasource.username=postgres
spring.datasource.password=#Diwa@1593

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.com.astra.ai=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# JWT Configuration
# ===============================
#jwt.secret=${JWT_SECRET}
#jwt.expiration=${JWT_EXPIRATION}
jwt.secret=2nX6M8vQ1aP9sR4tY7uK5wE8zH3cL6dF0bN2mJ9xV4qT7yP1kR5sU8wA3eG6hC9
jwt.expiration=86400000

# ===============================
# Default Admin
# ===============================
#app.admin.email=${APP_ADMIN_EMAIL}
#app.admin.password=${APP_ADMIN_PASSWORD}
app.admin.email=admin@astra.ai
app.admin.password=Admin@123

##########################################
# Gemini
##########################################

# spring.ai.model.chat=google-genai
# spring.ai.google.genai.api-key=${GEMINI_API_KEY}
# spring.ai.google.genai.chat.model=gemini-2.5-flash-lite
# spring.ai.google.genai.chat.temperature=0.7
# spring.ai.google.genai.chat.max-output-tokens=2048


##################################################
# Astra AI
##################################################

astra.ai.provider=OLLAMA

##################################################
# Spring AI
##################################################

spring.ai.model.chat=ollama

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2